<?php
	$rcmessages = array(0=>"Los campos con * son obligatorios.",
            1=>"El registro ya existe.",
			2=>"El registro no existe o no es accesible.",
			3=>"Operaci&oacute;n realizada con &eacute;xito",
			4=>"La informaci&oacute;n digitada no es aceptada por el sistema.",
			5=>"La direcci&oacute;n de e-mail no es v&aacute;lida.",
			6 => "No ha digitado la identificaci&oacute;n del cliente.",
			7=>"La fecha ingresada no es correcta.",
            8=>'Seguro desea modificar el registro?.',
            9=>'Seguro desea eliminar el registro?.',
            10=>'No se puede eliminar el cliente, tiene contactos asociados.',
            11=>'No se puede eliminar el contacto, tiene casos asociados.',
            12 => "El cliente no existe.",
            13 => 'El contrato no existe.',
            14 => "No ha digitado el n&uacute;mero del contrato",
            15=>"No se pudo realizar la operaci&oacute;n, el n&uacute;mero de identificaci&oacute;n est&aacute; relacionado a otro acudiente/reclamante.",
            16=>'La direcci&oacute;n de e-mail no es v&aacute;lida.',
            17=>'La longitud del nombre no es adecuada, modif&iacute;quelo e int&eacute;ntelo nuevamente',
            18=>'La longitud del primer nombre no es adecuada, modif&iacute;quelo e int&eacute;ntelo nuevamente',
            19=>'La longitud del segudo nombre no es adecuada, modif&iacute;quelo e int&eacute;ntelo nuevamente',
            20=>'La longitud del primer apellido no es adecuada, modif&iacute;quelo e int&eacute;ntelo nuevamente',
            21=>'La longitud del segundo apellido no es adecuada, modif&iacute;quelo e int&eacute;ntelo nuevamente',
            22=>'La edad no es v&aacute;lida, modif&iacute;quela e int&eacute;ntelo nuevamente',
            23=>"No existen datos para esta consulta.",
            24=>"El solicitante ya existe.",
            25=>"No se pudo realizar la operaci&oacute;n, el n&uacute;mero de identificaci&oacute;n est&aacute; relacionado a otro cliente.",
            33=>'Seguro desea modificar el registro?.',
            34=>'Seguro desea eliminar el registro?.',
            35=>'No se puede eliminar el Paciente, tiene casos asociados.',
            36=>'El paciente fue ingresado de forma correcta pero no se pudo registrar como acudiente/reclamante, consulte con el administrador del sistema.',
            37=>'El n&uacute;mero de historia cl&iacute;nica est&aacute; asociado a otro paciente, modif&iacute;quelo e int&eacute;ntelo nuevamente.',
            100=>"No se pudo realizar la operaci&oacute;n.");
?>