<?php
/*
 This is the language's file to the  Recurso table
*/
$rclabels = array("title"=>"Consolidado de compromisos",
				  "consulttitle"=>"",
				  "context_help"=>"El Consolidado informa de la gesti&oacute;n que a la fecha se le ha realizado a los casos.<br><B>Nota: </B>Recuerde que los campos marcados con asterisco ( * ) son obligatorios.",
"ordefecingdini"=>array("label"=>"Fecha inicial","accesskey"=>true,"commentary"=>""),
"ordefecingdfin"=>array("label"=>"Fecha final","accesskey"=>true,"commentary"=>""),
"periodo"=>array("label"=>"Periodo","accesskey"=>true,"commentary"=>""),
"orgacodigos"=>array("label"=>"Dependencia","accesskey"=>true,"commentary"=>""),
"titulo1"=>array("label"=>"GESTI&Oacute;N EN ","accesskey"=>false,"commentary"=>""),
"titulo2"=>array("label"=>"CONSOLIDADO PER&Iacute;ODO","accesskey"=>false,"commentary"=>""),
"titulo3"=>array("label"=>"POR TIPO DE CASOS RECIBIDOS","accesskey"=>false,"commentary"=>""),
"titulo4"=>array("label"=>"GESTI&Oacute;N DE SOLUCI&Oacute;N DE LAS TAREAS POR ESTADO","accesskey"=>false,"commentary"=>""),
"titulo5"=>array("label"=>"GESTI&Oacute;N DE SOLUCI&Oacute;N DE LOS SEGUIMIENTOS POR T&Eacute;RMINOS DE ATENCI&Oacute;N","accesskey"=>false,"commentary"=>""),
"titulo6"=>array("label"=>"RECEPCI&Oacute;N DE LOS CASOS (Medio y Tipo)","accesskey"=>false,"commentary"=>""),
"titulo7"=>array("label"=>"GESTI&Oacute;N EN TODAS LAS DEPENDENCIAS","accesskey"=>false,"commentary"=>""),
"titulo8"=>array("label"=>"POR TIPO DE CASOS Y TIPOS DE COMPROMISO","accesskey"=>false,"commentary"=>""),
"tiporeq"=>array("label"=>"TIPO DE CASO","accesskey"=>false,"commentary"=>""),
"commitment"=>array("label"=>"TIPO DE COMPROMISO","accesskey"=>false,"commentary"=>""),
"estado"=>array("label"=>"ESTADO","accesskey"=>false,"commentary"=>""),
"atencion"=>array("label"=>"T&Eacute;RMINO DE ATENCION","accesskey"=>false,"commentary"=>""),
"medio"=>array("label"=>"MEDIO DE RECEPCI&Oacute;N","accesskey"=>false,"commentary"=>""),
"dentro"=>array("label"=>"FINALIZADOS DENTRO DEL T&Eacute;RMINO","accesskey"=>false,"commentary"=>""),
"fuera"=>array("label"=>"FINALIZADOS FUERA DEL T&Eacute;RMINO","accesskey"=>false,"commentary"=>""),
"pendnovenci"=>array("label"=>"PENDIENTES NO VENCIDAS","accesskey"=>false,"commentary"=>""),
"pendvenci"=>array("label"=>"PENDIENTES VENCIDAS","accesskey"=>false,"commentary"=>""),
"pietiporeq"=>array("label"=>"%* = Participaci&oacute;n del total de casos recibidos con seguimiento por tipo en el total de casos con seguimiento recibidos por la empresa.","accesskey"=>false,"commentary"=>""),
"pierecepcion"=>array("label"=>"Participaci&oacute;n del total de seguimientos seg&uacute;n su medio de recepci&oacute;n en el total de seguimientos generados en la empresa.","accesskey"=>false,"commentary"=>""),
"pieatencion"=>array("label"=>"%* = Participaci&oacute;n del total de seguimientos seg&uacute;n su t&eacute;rmino de atenci&oacute;n en el total de seguimientos realizados por la empresa.","accesskey"=>false,"commentary"=>""),
"acumulado"=>array("label"=>"ACUMULADO","accesskey"=>false,"commentary"=>""),
"no"=>array("label"=>"No","accesskey"=>false,"commentary"=>""),
"porcentaje"=>array("label"=>"%*","accesskey"=>false,"commentary"=>""),
"total"=>array("label"=>"TOTAL","accesskey"=>false,"commentary"=>""),
"suma"=>array("label"=>"E","accesskey"=>false,"commentary"=>""),
"sumapor"=>array("label"=>"E%","accesskey"=>false,"commentary"=>""),
"darn"=>array("label"=>"DARN","accesskey"=>false,"commentary"=>""),
);
?>