<?php
/*
 This is the language's file to the  Causa table
*/
$rclabels = array("title"=>"Administraci&oacute;n de par&aacute;metros",
				  "consulttitle"=>"Administraci&oacute;n de par&aacute;metros",
				  "context_help"=>"Estos son los par&aacute;metros del sistema.<br>Seleccione el contexto y proceda a hacer sus cambios.<br>Para guardar sus cambios presione MODIFICAR.",
"schema"=>array("label"=>"Contexto","accesskey"=>true,"commentary"=>""),
"emprtelefos" => array("label"=>"Tel&eacute;fono","accesskey"=>true,"commentary"=>""),
"SUFIJO_ORDENUMEROS" => array("label"=>"Sufijo del c&oacute;digo de caso","accesskey"=>true,"commentary"=>"Sufijo de identificaci&oacute;n del codigo de caso"),
"horario_atencion" => array("label"=>"Horario atenci&oacute;n","accesskey"=>false,"commentary"=>""),
"hora_ini" => array("label"=>"Hora de inicio de atenci&oacute;n","accesskey"=>true,"commentary"=>"HH:MM"),
"hora_fin" => array("label"=>"Hora de fin de atenci&oacute;n","accesskey"=>true,"commentary"=>"HH:MM"),
"email_server" => array("label"=>"DNS servidor de email","accesskey"=>true,"commentary"=>""),
"empresa" => array("label"=>"Informaci&oacute;n de la empresa","accesskey"=>false,"commentary"=>""),
"dump_program" => array("label"=>"Ruta ejecutable de copia de seguridad","accesskey"=>true,"commentary"=>""),
"SPLASH_IMG" => array("label"=>"Imagen inicial","accesskey"=>true,"commentary"=>""),
"web_user_conf" => array("label"=>"Informaci&oacute;n de usuario web","accesskey"=>false,"commentary"=>""),
"user" => array("label"=>"Usuario web","accesskey"=>true,"commentary"=>""),
"dep_detalle" => array("label"=>"Dependencias para reporte detallado","accesskey"=>true,"commentary"=>""),
"MAXLENGTH_ORDENUMEROS" => array("label"=>"Tama&ntilde;o del c&oacute;digo de caso","accesskey"=>true,"commentary"=>""),
"type_close" => array("label"=>"Tipos de caso","accesskey"=>true,"commentary"=>"Tipos de caso prohibidos en el ingreso web"),
"DEFAUL_CUSTOMER" => array("label"=>"Informaci&oacute;n del cliente","accesskey"=>true,"commentary"=>""),
"ORG_INACT" => array("label"=>"Estados inactivos para las dependencias","accesskey"=>true,"commentary"=>""),
"EST_GRUP_INA" => array("label"=>"Estados inactivos para los grupos","accesskey"=>true,"commentary"=>""),
"acceso_total" => array("label"=>"Dependencias","accesskey"=>true,"commentary"=>"Dependencias que pueden ver toda la organizaci&oacute;n"),
"emprnits" => array("label"=>"NIT","accesskey"=>true,"commentary"=>"Con puntos y gui&oacute;n"),
"emprnombres" => array("label"=>"Nombre de la empresa","accesskey"=>true,"commentary"=>""),
"emprdireccs" => array("label"=>"Direcci&oacute;n","accesskey"=>true,"commentary"=>""),
"emprfaxs" => array("label"=>"Fax","accesskey"=>true,"commentary"=>""),
"emprnombreps" => array("label"=>"Nombre del representante","accesskey"=>true,"commentary"=>""),
"emprlogos" => array("label"=>"Logo","accesskey"=>true,"commentary"=>""),
"empremail" => array("label"=>"Email","accesskey"=>true,"commentary"=>"usuario@dominio.com"),
"email_pass" => array("label"=>"Contrase&ntilde;a usuario servidor de email","accesskey"=>true,"commentary"=>""),

"orgacodigos" => array("label"=>"Dependencia","accesskey"=>true,"commentary"=>""),
"merecodigos" => array("label"=>"Medio de recepci&oacute;n","accesskey"=>true,"commentary"=>""),
"ticlcodigos" => array("label"=>"Tipo de cliente","accesskey"=>true,"commentary"=>""),
"esclcodigos" => array("label"=>"Estado de cliente","accesskey"=>true,"commentary"=>""),
"locacodigos" => array("label"=>"Localizaci&oacute;n","accesskey"=>true,"commentary"=>""),
"tiidcodigos" => array("label"=>"Tipo de identificaci&oacute;n","accesskey"=>true,"commentary"=>""),
"clienombres" => array("label"=>"Nombre","accesskey"=>true,"commentary"=>""),
"TYPES_CASE_PURSUIT" => array("label"=>"Seguimiento","accesskey"=>true,"commentary"=>"Tipos de caso que se considera como de seguimiento"),
"TYPES_CASE_DENUNCIA" => array("label"=>"Tipos de caso que requieren Solicitante/Denunciante","accesskey"=>true,"commentary"=>"Tipos de caso que requieren de un Solicitante/Denunciante"),
"DENUNCIA_TC" => array("label"=>"Denuncias","accesskey"=>true,"commentary"=>"Tipos de caso considerados como DENUNCIA"),
"TRACKING_ALLOWED_STATES" => array("label"=>"Estado de caso","accesskey"=>true,"commentary"=>"Estados del caso en los que es permitido realizar seguimientos"),
"CLOSE_COMMITMENT_STATES" => array("label"=>"Estado de tarea","accesskey"=>true,"commentary"=>"Estados de la tarea en los que se da por cumplido un compromiso"),
"NO_CLOSE_COMMITMENT_STATES" => array("label"=>"Estado de tarea","accesskey"=>true,"commentary"=>"Estados de la tarea en los que se da por no cumplido un compromiso"),
"TAREA_SEGUIMIENTO" => array("label"=>"Tarea de Seguimiento","accesskey"=>true,"commentary"=>"Tarea considerada de seguimiento"),
"ASAPPOINTS_DEFAULT" => array("label"=>"Dependencias que asignan citas electr&oacute;nicas","accesskey"=>true,"commentary"=>"Dependencias encargadas de asignar las citas ingresadas por los ciudadanos desde el Web."),
"OPOSITE_ACTIVITIES" => array("label"=>"Actividades opuestas","accesskey"=>false,"commentary"=>""),
"CANT_DIAS_ING" => array("label"=>"Cantidad de d&iacute;as para ingreso de caso","accesskey"=>true,"commentary"=>"Cantidad de d&iacute;as de anterioridad permitidos para el ingreso del caso a partir de la fecha de actual."),
"RESP_ABIERTA"=> array("label"=>"Respuesta abierta","accesskey"=>true,"commentary"=>"Seleccione la respuesta que ser&aacute; presentada en la interfaz de configuraci&oacute;n de encuestas como respuesta abierta."),
"OBJ_PREG_ABIERTA"=> array("label"=>"Objetos para pregunta abierta","accesskey"=>true,"commentary"=>"Seleccione los objetos que se deben usar para presentar la respuesta de pregunta abierta."),
"OBJ_PREG_CERRADA"=> array("label"=>"Objetos para pregunta cerrada","accesskey"=>true,"commentary"=>"Seleccione los objetos que se deben usar para presentar las respuestas de una pregunta cerrada."),
"SMS_WS_PATH"=> array("label"=>"Ruta Web Service para env&iacute;o de Mensajes de texto","accesskey"=>true,"commentary"=>""),
"DEFAULT_STATUS"=> array("label"=>"Estados por defecto de la tarea","accesskey"=>true,"commentary"=>"Estados de la tarea que permiten registrar atenciones sin que ocurra un cambio de tarea."),
"COD_LOCALIZ_CALI" => array("label"=>"C&oacute;digo de localizaci&oacute;n de Cali","accesskey"=>true,"commentary"=>""),
"USER_DOCUNET"=> array("label"=>"Usuario para el sistema DOCUNET","accesskey"=>true,"commentary"=>"Usuario que registra documentos en el sistema DCUNET"),
"DOCUNET_PATH"=> array("label"=>"Ruta para consulta de archivos en Docunet","accesskey"=>true,"commentary"=>""),
"TAREA_CC" => array("label"=>"Tarea de Control y Cierre","accesskey"=>true,"commentary"=>"Se parametriza la tarea de control y cierre para que el reporte consolidado  y de tallado no la tengan en cuenta al determinar la dependencia que actualmente tiene asignado un caso."),
"ORG_INACT_DEFAULT" => array("label"=>"Estado inactivo de la dependencia por defecto","accesskey"=>true,"commentary"=>""),
"TIP_DEP_FISICA" => array("label"=>"Tipos de dependencia f&iacute;sica","accesskey"=>true,"commentary"=>"Son los tipos de dependencia que la califican como dependencia f&iacute;sica."),
"SERV_ORG" => array("label"=>"Servicios","accesskey"=>true,"commentary"=>"Entes organizacionales considerados como servicios dentro de la organizaci&oacute;n"),
"CANT_DIAS_ALERTA"=> array("label"=>"Alerta de vencimiento","accesskey"=>true,"commentary"=>"Cantidad de d&iacute;as antes del vencimiento de un caso en elque se debe activar la alerta."),
"EMAIL_ALERTA1"=> array("label"=>"Correo de alerta 1","accesskey"=>true,"commentary"=>"Correo al que debe llegar el listado de casos pr&oacute;ximos a vencerse."),
"EMAIL_ALERTA2"=> array("label"=>"Correo de alerta 2","accesskey"=>true,"commentary"=>"Correo al que debe llegar el listado de casos pr&oacute;ximos a vencerse."),
);
?>