<?php
$rcmessages = array(0=>"Los campos con * son obligatorios.",
					1=>"El registro ya existe.",
					2=>"El registro no existe o no es accesible.",
					3=>"Operaci&oacute;n realizada con &eacute;xito.",
					4=>"La informaci&oacute;n digitada no es aceptada por el sistema.",
					5=>"No se cuenta con la suficiente informaci&oacute;n para eliminar el registro. Por favor cons&uacute;ltelo primero.",
					6=>"No se puede actualizar el registro por que existen relaciones de dependencias con ese grupo.",
					7=>"La fecha ingresada es incorrecta.",
					8=>"No se cuenta con la suficiente informaci&oacute;n para modificar el registro. Por favor cons&uacute;ltelo primero.",
					9=>"Usted no puede modificar el c&oacute;digo del grupo. Pos&iacute;blemente lo que se desea es crear un nuevo grupo o cambiarle el estado al grupo actual.",
					10=>"No se puede eliminar el grupo pues ha sido relacionado a una dependencia.",
					11=>"Existe ya una persona como responsable del grupo. Por favor modifique el registro correspondiente.",
					12=>"Un empleado no pude estar varias veces en el mismo grupo. Por favor modifique el registro correspondiente.",
					13=>'La direcci&oacute;n de e-mail no es v&aacute;lida.',
                    14=>'Seguro desea modificar el registro?.',
                    15=>'Seguro desea eliminar el registro?.',
                    16=>'No se pudo realizar la operaci&oacute;n, la dependencia es usada en los casos.',
                    17=>'No se pudo realizar la operaci&oacute;n, el grupo no tiene personal asignado.',
                    18=>"No se puede modificar esta dependencia, la dependencia padre no est&aacute; activa. Active la dependencia VAR1 primero.",
                    19=>"No se pudo realizar la operaci&oacute;n, el n&uacute;mero de identificaci&oacute;n est&aacute; relacionado a otro empleado.",
                    20=>"No se pudo realizar la operaci&oacute;n, el usuario est&aacute; relacionado a otro empleado.",
                    21=>"Esta dependencia presenta casos pendientes por resolver. Dichos casos ser&aacute;n transferidos a su dependencia padre. ¿Seguro desea continuar?",
					22=>"No se pudo realizar la operaci&oacute;n. Las dependencias f&iacute;sicas no se deben mover.",
					23=>"No se pudo realizar la operaci&oacute;n. Un ente organizacional no puede ser padre de otro ente organizacional.",
					24=>"No se pudo realizar la operaci&oacute;n. La dependencia seleccionada es igual a la dependencia padre actual.",
					25=>"No se pudo realizar la operaci&oacute;n. La dependencia padre no se puede modificar. Utilice el bot&oacute;n MOVER.",
					26=>"No se pudo realizar la operaci&oacute;n. No se han configurado los tipos dedependencia f&iacute;sica, consulte con el administrador del sistema.",
					27=>"Transferencia generada por movimiento de dependencia.",
					28=>"Al inactivar la dependencia tambi&eacute;n se inactivaran las dependencias que est&aacute;n bajo ella, ¿Desea continuar con esta operaci&oacute;n?",
					100=>"No se pudo realizar la operaci&oacute;n.",
);
?>